#
#Sun Oct 15 22:31:49 CST 2017
SQL=SELECT PATIENT_ID AS brid, VISIT_ID AS zyid, SHIFT_DATE AS jiaobandate\r\n  FROM SHIFT_EXCHANGE_RECORD_DETAIL\r\n WHERE PATIENT_ID \= '%s'\r\n   AND VISIT_ID \= %s\r\n ORDER BY shift_date DESC
